.ifndef CHARMAP_INC
CHARMAP_INC = 1

; ASCII-PETSCII character map
.charmap $40, $0
.charmap $41, $1
.charmap $42, $2
.charmap $43, $3
.charmap $44, $4
.charmap $45, $5
.charmap $46, $6
.charmap $47, $7
.charmap $48, $8
.charmap $49, $9
.charmap $4a, $a
.charmap $4b, $b
.charmap $4c, $c
.charmap $4d, $d
.charmap $4e, $e
.charmap $4f, $f
.charmap $50, $10
.charmap $51, $11
.charmap $52, $12
.charmap $53, $13
.charmap $54, $14
.charmap $55, $15
.charmap $56, $16
.charmap $57, $17
.charmap $58, $18
.charmap $59, $19
.charmap $5a, $1a

.endif
